config/routes.rb
Rails.application.routes.draw do

  resources :notifications
  resources :reviews
  resources :messages, except: [:show]
  get '/messages/inbox', to: 'messages#inbox', as: "inbox"
  get '/messages/:receiver_id', to: 'messages#message_thread', as: "message_thread"
  resources :donations
  resources :users do
    get '/donations', to: 'users#donations', as: "donations"
    get '/morph', to: 'users#morph', as: "morph"
  end
  get '/', to: 'static#index'
  get '/login', to: 'static#login'
  post '/login', to: 'static#attempt_login'
  get '/logout', to: 'static#logout'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, :class_name => "User", :foreign_key => "sender_id"
  belongs_to :receiver, :class_name => "User", :foreign_key => "receiver_id"

  has_many :notifications, as: :content, dependent: :destroy
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_flash_user, only: [:new]

  def new
    @message = Message.new
    @other_users = User.all_not(current_user)
  end

  def create
    user = current_user
    @message = current_user.new_message(message_params)
    if @message.save
      current_user.create_notification(@message.receiver, @message)
      redirect_to message_thread_path(@message.receiver)
    else
      render :new
    end
  end

  def inbox
    other_users = User.all_not(current_user)
    @user = current_user
    @users_corresponded_with = @user.messages_sent.collect {|m| other_users.find(m.receiver_id)}
    @users_corresponded_with << @user.messages_received.collect {|m| other_users.find(m.sender_id)}
    @users_corresponded_with.flatten!.uniq!
  end

  def message_thread
    @user = current_user
    @receiver = User.find(params[:receiver_id])
    messages = Message.all.select {|m| m.sender == @user && m.receiver == @receiver}
    messages << Message.all.select {|m| m.sender == @receiver && m.receiver == @user}
    messages.flatten!
    @messages_sorted = messages.sort_by {|m| m.created_at}.reverse
    current_user.clear_message_notifications(@receiver)
  end

  private

  def message_params
    params.require(:message).permit(:receiver_id, :title, :content)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/inbox.erb
<div class="centered">
  <h2 class="header">My Conversations</h2><br>
  <div class="button"><%= link_to "Send A New Message", new_message_path%></div>
</div>

<% @users_corresponded_with.each do |user| %>
<a class="message-specific" href="/messages/<%=user.id%>">
<div class="message-specific">

      <div class="message-sender"><%= user.username%></div>
      <% if current_user.message_notifications_with(user).count > 0 %>
        <span class="number-bubble"><%=current_user.message_notifications_with(user).count%></span>
      <% end %>
      <% recent_message = current_user.chronological_messages(user).first %><br>

      <div class="speech-bubble speech-bubble-left little-bubble">
        <!-- <img class="thread-profile" src="<%=recent_message.sender.profile_picture_url%>" alt=""> -->
        <%= max_length(recent_message.content, 40)%>
      </div>

</div>
</a>

<% end %>

app/views/messages/message_thread.erb
<% flash[:receiver_id] = @receiver.id %>
<div class="centered">
  <div class="header">
    <h3 class="message-thread-header"> My Conversation With <%= link_to @receiver.username, user_path(@receiver) %></h3>
  </div>
  <div class="reply-container">
    <div class="button">
      <%= link_to "Reply", new_message_path %>
    </div>
</div>


</div>

  <% @messages_sorted.each do |message| %>

      <img class='thread-profile <%= "profile-#{message.sender == current_user ? 'left' : 'right'}"%>' src="<%=message.sender.profile_picture_url%>" alt="<%=message.sender.username%>'s picture'">
        <span class="speech-bubble <%= message.sender == current_user ? 'speech-bubble-left' : 'speech-bubble-right'%>">
        <b><%= message.sender.username %></b> - <%= message.created_at.strftime("%e %b %Y, %l:%M %p") %><br>
      <p> <%= message.content %> </p> </span>
  <% end %>

app/views/messages/new.html.erb
<div class="centered">
  <h3 class="header">New &nbsp&nbsp&nbspMessage</h3><br>

  <%= form_for @message do |f| %>
    <div>
      <%= f.label "Send Message To" %>
      <%= f.collection_select(:receiver_id, @other_users, :id, :username, {:selected => @receiver_id}) %>
    </div>
    <div>
      <%= f.label "Message" %>
      <%= f.text_area :content, size: "40x5" %>
    </div>

    <div class="message-submit">
      <%= f.submit%>
    </div>

  <% end %>
</div>