config/routes.rb
Rails.application.routes.draw do

  resources :notifications
  resources :reviews
  resources :messages, except: [:show]
  get '/messages/inbox', to: 'messages#inbox', as: "inbox"
  get '/messages/:receiver_id', to: 'messages#message_thread', as: "message_thread"
  resources :donations
  resources :users do
    get '/donations', to: 'users#donations', as: "donations"
    get '/morph', to: 'users#morph', as: "morph"
  end
  get '/', to: 'static#index'
  get '/login', to: 'static#login'
  post '/login', to: 'static#attempt_login'
  get '/logout', to: 'static#logout'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, confirmation: true

  has_many :donations_made, :class_name => "Donation", :foreign_key => "sender_id", dependent: :destroy
  has_many :donations_received, :class_name => "Donation", :foreign_key => "receiver_id", dependent: :destroy

  has_many :messages_sent, :class_name => "Message", :foreign_key => "sender_id", dependent: :destroy
  has_many :messages_received, :class_name => "Message", :foreign_key => "receiver_id", dependent: :destroy

  has_many :reviews_written, :class_name => "Review", :foreign_key => "writer_id", dependent: :destroy
  has_many :reviews, :class_name => "Review", :foreign_key => "user_id", dependent: :destroy

  has_many :notifications

  def new_donation(params)
    Donation.new(sender: self, receiver_id: params[:receiver_id], amount: params[:amount], content: params[:content])
  end

  def new_message(params)
    Message.new(sender: self, receiver_id: params[:receiver_id], title: params[:title], content: params[:content])
  end

  def new_review(params)
    Review.new(writer: self, user_id: params[:user_id], rating: params[:rating], content: params[:content])
  end

  def create_notification(user, content)
    Notification.create(user: user, content: content)
  end

  def active_notifications
    notifications.where(active: true)
  end

  def clear_notifications(n)
    n.each do |notification|
      notification.update(active: false)
    end
  end

  def clear_message_notifications(user)
    message_notifications.each {|notification|
      if !notification.content.nil? && notification.content.receiver == self && notification.content.sender == user
        notification.update(active: false)
      end
    }
  end

  def clear_review_notifications
    clear_notifications(review_notifications)
  end

  def clear_donation_notifications
    clear_notifications(donation_notifications)
  end

  def message_notifications_with(user)
    messages = message_notifications.map do |notification|
      notification.content
    end
    messages.select {|message|
      !message.nil? && message.receiver == self && message.sender == user
    }
  end

  def message_notifications
    @n = notifications.where(active: true, content_type: "Message")
    @n.select{|m| !m.nil? }
  end

  def donation_notifications
    notifications.where(active: true, content_type: "Donation")
  end

  def review_notifications
    notifications.where(active: true, content_type: "Review")
  end

  def self.all_not(user)
    User.where.not(id: user.id)
  end

  def chronological_messages(user)
    messages.select{|m| m.sender == user || m.receiver == user}.sort_by {|m| m.created_at}.reverse
  end

  def average_review_score
    if reviews.count == 0
      "No reviews yet!"
    else
      sum = reviews.inject(0) {|acc, review|
        acc + review.rating
      }
      sum = sum.to_f
      "#{(sum /= reviews.count).round(1)}/5 Stars"
    end
  end

  def messages
    messages_sent + messages_received;
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  before_action :redirect_if_not_login, except: [:new, :create]
  before_action :is_own_page, only: [:show]

  def index
    if params[:search]
      search = params[:search].downcase
      @users = User.all.select{|user|
        user.username.downcase.include?(search) || user.profession.downcase.include?(search)
      }
    else
      @users = User.all
    end

  end

  def show
    @reviews = @user.reviews.sort_by {|review| review.created_at}.reverse
    if is_own_page
      @notifications = current_user.active_notifications
      current_user.clear_review_notifications
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    if current_user == @user
      @user.destroy
      session.delete :user_id
    end
    redirect_to users_path
  end

  def morph
    @user = User.find(params[:user_id])
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :profession, :location, :profile_picture_url, :password, :password_confirmation)
  end

  def is_own_page
    @is_own_page = @user == User.find(session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="user-form">
  <%= form_for user do |f| %>
    <div class="">
      <%= f.label "User Name" %>
      <%= f.text_field :username %>
    </div>
    <div class="">
      <%= f.label "Profession" %>
      <%= f.text_field :profession %>
    </div>
    <div class="">
      <%= f.label "Location" %>
      <%= f.text_field :location %>
    </div>
    <div class="">
      <%= f.label "Profile URL" %>
      <%= f.text_field :profile_picture_url %>
    </div>

    <div class="">

    </div>
    <div class="">
      <%= f.label "Password" %>
      <%= f.password_field :password %> <br>
      <%= f.label "Confirm Password" %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="user-submit">
      <%= f.submit%>
    </div>

  <% end %>
</div>

app/views/users/edit.html.erb
<div class="centered">
  <h3 class="header">Edit &nbsp&nbsp&nbspProfile</h3>
  <%= render partial: 'form', locals:{user: @user} %>
</div>

app/views/users/index.html.erb
<div class="centered">
  <h2 class="header">Users</h2>
</div>
<div class="index-block">
  <% if @users.empty? %>
  <div class="alert">
    "No users here!"
  </div>
  <% end %>
  <% @users.each do |user| %>
  <div class="index-item">
    <img class="index-pic" src="<%=user.profile_picture_url%>" alt="">
    <div class="index-item-text">
      <h3 class="header"><%= link_to user.username, user_path(user)%></h3><br>
      <span style="margin: 10px">
        <%= "#{user.profession} in #{user.location}"%>
      </span>
      <span style="float: right">
        <%=user.average_review_score%>
      </span>
    </div>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="centered">
  <h2 class="header">Create New User</h2>
  <%= render partial:'form', locals:{user: @user} %>
</div>

app/views/users/show.html.erb
<div class="top-profile-page">
  <h2 class="header"><%=@user.username%></h2>

  <img class="profile-pic" src="<%=@user.profile_picture_url%>" alt=""><br>

  <h4 class="user-show-header"> <%= "#{@user.profession} in #{@user.location}"%> </h4>

  <% if !@is_own_page %>
    <% flash[:receiver_id] = @user.id %>
    <div class="button-smaller"><%= link_to("Review This User", new_review_path) %></div>

    <div class="button-smaller"><%= link_to("Donate To This User", new_donation_path) %></div>

    <div class="button-smaller"><%= link_to "Become This User", user_morph_path(@user) %></div>
  <% end %>

  <% if @is_own_page %>
    <div class="center"><%= button_to "Delete", {controller: :users, action: 'destroy', id: @user.id }, method: :delete, data: {confirm: "Are you sure you want to delete your account?" }%></div>
  <% end %>
  <hr>
</div>


<div class="reviews-profile-page">
  <h3 class="user-show-header">Reviews</h3>
  <div class="reviews_div">
    <% if !@reviews.empty? %>
      <% @reviews.each do |review| %>
        <div class="review-show">
          <span style="font-size: 24px"> <%= link_to review.writer.username, user_path(review.writer) %> </span> <span> says...</span>
          <span style="float: right"> <%= review.created_at.strftime("%e %b %Y, %l:%M %p")%></span><br>
          <span style="float: left"> <%= review.content %> </span>
          <span style="float: right"> <%= "#{review.rating}/5 Stars" %> </span>
        </div>
      <% end %>
    <% else %>
      <div class="no-reviews">
        No reviews yet!  Check back later.
      </div>
    <% end %>
  </div>
</div>