config/routes.rb
Rails.application.routes.draw do

  resources :notifications
  resources :reviews
  resources :messages, except: [:show]
  get '/messages/inbox', to: 'messages#inbox', as: "inbox"
  get '/messages/:receiver_id', to: 'messages#message_thread', as: "message_thread"
  resources :donations
  resources :users do
    get '/donations', to: 'users#donations', as: "donations"
    get '/morph', to: 'users#morph', as: "morph"
  end
  get '/', to: 'static#index'
  get '/login', to: 'static#login'
  post '/login', to: 'static#attempt_login'
  get '/logout', to: 'static#logout'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Underthetable</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 main-navbar" style="z-index: 10;">
          <a class="navbar-brand dn-title" href="<%=users_path%>">Donation Nation</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
              <% if logged_in? %>
              <%= form_tag(users_path, method: "get") do%>
                <%= text_field_tag :search, nil, placeholder: "Search Users..."%>
                <%= submit_tag "Search" %>
              <% end %>

              <!-- <li>
                <a class="nav-link" href="/notifications"><%="#{pluralize(current_user.active_notifications.count, "Notification")} Pending"%></a>
              </li> -->

            </ul>
            <ul class="nav navbar-nav navbar-right">

              <li class="spaced-nav">
                <a class="nav-link" href="<%=inbox_path%>">
                  <% if current_user.message_notifications.count != 0 %>
                    <span class="number_bubble"><%= current_user.message_notifications.count %></span>
                  <% end %>
                  <%= fa_icon "envelope-o"%>
                </a>
              </li>
              <li class="spaced-nav">
                <a class="nav-link" href="<%=donations_path%>">
                  <% if current_user.donation_notifications.count != 0 %>
                    <span class="number_bubble"><%= current_user.donation_notifications.count %></span>
                  <% end %>
                  <%= fa_icon "usd"%>
                </a>
              </li>
              <li class="spaced-nav">
                <a class="nav-link" href="<%=user_path(current_user)%>">
                  <% if current_user.review_notifications.count != 0 %>
                    <span class="number_bubble"><%= current_user.review_notifications.count %></span>
                  <% end %>
                  <%= fa_icon "bullhorn"%>
                </a>
              </li>
              <li class= "rightmost">
                <div class="dropdown show">
                  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%=current_user.username %> <%=fa_icon "user-circle"%>
                  </a>

                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                    <span class="dropdown-item disabled" id="balance-span"><%="Balance: $#{current_user.balance}"%></span>
                    <a class="dropdown-item" href="<%=user_path(current_user)%>">My Profile</a>
                    <a class="dropdown-item" href="<%=edit_user_path(current_user)%>">Edit My Profile</a>
                    <a class="dropdown-item" href="<%=logout_path%>">Log Out</a>
                  </div>
                </div>
              </li>
              <% end %>
            </ul>
          </div>
        </nav>
        <div class="down-60"></div>
    <!-- <img src="https://upload.wikimedia.org/wikipedia/en/2/20/Sierra_Mist_2018_Logo.png" alt=""> -->
    <%= yield %>
  </body>
</html>